####
# ATENTION:
# Replace all occurences of modularized with your project's name
####

# v2 syntax
version: '2'

# Named volumes
volumes:
  # Postgres Data
  modularized-postgres-data:
    driver: local

  # MySQL Data
  modularized-mysql-data:
    driver: local

  # Redis Data
  modularized-redis-data:
    driver: local

services:

  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: modularized-mysql
    volumes:
      - modularized-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=modularized
      - MYSQL_USER=modularized
      - MYSQL_PASSWORD=modularized

  # Redis
  redis:
    image: ambientum/redis:3.2
    container_name: modularized-redis
    command: --appendonly yes
    volumes:
      - modularized-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Nginx)
  app:
    image: ambientum/php:7.1-nginx
    container_name: modularized-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
      - redis

  # Laravel Queues
  queue:
    image: ambientum/php:7.1
    container_name: modularized-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - redis